import {test,expect} from '@playwright/test';
test.describe.serial('FlowDesk 完整链路',()=>{
 test('Dashboard KPI 与最近流程进入编辑器',async({page})=>{await page.goto('/');await expect(page.getByTestId('kpi-grid')).toBeVisible();await expect(page.getByText('流程总数')).toBeVisible();await expect(page.getByText('异常实例',{exact:true}).first()).toBeVisible();await page.getByTestId('recent-workflow').first().click();await expect(page.getByTestId('flow-canvas')).toBeVisible();});
 test('审批配置、保存和双区域校验',async({page})=>{await page.goto('/workflows/wf-1');await page.getByTestId('canvas-node-approval').click();await expect(page.getByTestId('config-panel')).toContainText('审批配置');await page.getByLabel('审批人来源').selectOption({label:'固定角色'});await page.getByTestId('save-node-config').click();await page.getByRole('button',{name:'保存草稿'}).click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('canvas-node-condition')).toHaveClass(/invalid/);await expect(page.getByTestId('issues-panel')).toContainText('条件分支规则未配置');const before=await page.getByTestId('error-count').textContent();expect(Number(before?.match(/\d+/)?.[0])).toBeGreaterThan(0);await page.getByTestId('canvas-node-condition').click();await page.getByLabel('条件字段').selectOption('amount');await page.getByLabel('条件比较值').fill('5000');await page.getByTestId('save-node-config').click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('error-count')).toContainText('0 错误');});
 test('预览只读且仅展示已校验草稿',async({page})=>{await page.goto('/workflows/wf-2/preview');await expect(page.getByTestId('preview-gate')).toBeVisible();await page.goto('/workflows/wf-2');await page.getByTestId('validate-button').click();await expect(page.getByTestId('error-count')).toContainText('0 错误');await page.goto('/workflows/wf-2/preview');await expect(page.getByTestId('preview-readonly')).toBeVisible();await expect(page.getByLabel('申请金额')).toBeDisabled();await expect(page.getByRole('button',{name:'模拟提交'})).toHaveCount(0);});
 test('发布后列表和总览同步',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('publish-button').click();await expect(page.getByRole('status')).toContainText('发布成功');await page.getByRole('link',{name:'流程管理'}).click();const row=page.getByTestId('workflow-row').filter({hasText:'采购合同审批'});await expect(row).toContainText('已发布');await expect(row).toContainText('v3');await page.getByRole('link',{name:'总览'}).click();await expect(page.getByTestId('kpi-grid')).toBeVisible();});
 test('异常实例详情、时间线与当前节点高亮',async({page})=>{await page.goto('/monitor');await page.getByRole('button',{name:'异常',exact:true}).click();await page.getByTestId('instance-row').first().click();await expect(page.getByTestId('instance-detail')).toBeVisible();await expect(page.getByTestId('execution-timeline')).toContainText('提交申请');await expect(page.locator('.runtime-highlight')).toHaveCount(1);await expect(page.getByTestId('field-snapshot')).toContainText('申请金额');});
 test('版本比较并恢复历史版本',async({page})=>{await page.goto('/workflows/wf-2/versions');await expect(page.getByTestId('version-compare')).toContainText('新增节点');await page.getByTestId('restore-version').click();await expect(page).toHaveURL(/\/workflows\/wf-2$/);await expect(page.getByRole('status')).toContainText('已恢复');await expect(page.getByTestId('flow-canvas')).toBeVisible();});
});
test.describe.serial('表单字段依赖审校台',()=>{
 test('字段改标识同步条件依赖',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-form').click();const row=page.getByTestId('field-row-amount');await row.getByLabel('字段标识').fill('totalAmount');await row.getByLabel('字段标识').press('Enter');await expect(page.getByRole('status')).toContainText('依赖已同步');await page.getByTestId('canvas-node-condition').click();await expect(page.getByLabel('条件字段')).toHaveValue('totalAmount');await expect(page.getByTestId('canvas-node-condition')).not.toHaveClass(/pending/);});
 test('移除字段使条件节点待修复，发布整批拒绝并列出旧新值',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-form').click();await page.getByTestId('field-row-amount').getByTitle('删除字段').click();await expect(page.getByTestId('canvas-node-condition')).toHaveClass(/pending/);await expect(page.getByTestId('repair-indicator')).toContainText('1 处字段依赖待修复');await page.getByTestId('publish-button').click();const rej=page.getByTestId('publish-rejection');await expect(rej).toBeVisible();await expect(rej).toContainText('采购合同审批');await expect(rej).toContainText('申请金额');await expect(rej).toContainText('金额判断');await expect(rej).toContainText('申请金额（金额）');await expect(rej).toContainText('字段已移除');await expect(page.locator('.draft-indicator')).toContainText('v2');await rej.getByRole('button',{name:'返回修复'}).click();await page.getByTestId('canvas-node-condition').click();await expect(page.getByTestId('repair-banner')).toContainText('申请金额');await page.getByLabel('修复字段').selectOption('reason');await page.getByTestId('resolve-repair').click();await page.getByTestId('validate-button').click();await expect(page.getByTestId('error-count')).toContainText('0 错误');await page.getByTestId('publish-button').click();await expect(page.getByRole('status')).toContainText('发布成功');await expect(page.locator('.draft-indicator')).toContainText('v3');});
 test('修改字段类型让引用节点待修复并记录旧新值',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-form').click();await page.getByTestId('field-row-amount').getByLabel('字段类型').selectOption('text');await expect(page.getByTestId('canvas-node-condition')).toHaveClass(/pending/);await page.getByTestId('canvas-node-condition').click();const banner=page.getByTestId('repair-banner');await expect(banner).toContainText('类型已变更');await expect(banner).toContainText('金额 → 文本');await page.getByTestId('validate-button').click();await expect(page.getByTestId('issues-panel')).toContainText('待修复');});
 test('实例详情沿用发布时字段快照，不展示新字段',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-form').click();await page.getByLabel('新字段名称').fill('加急说明');await page.getByLabel('新字段标识').fill('urgentNote');await page.getByTestId('add-field').click();await expect(page.getByTestId('field-row-urgentNote')).toBeVisible();await page.goto('/monitor');await page.getByRole('button',{name:'异常',exact:true}).click();await page.getByTestId('instance-row').filter({hasText:'INS-2026-0002'}).click();const snap=page.getByTestId('field-snapshot');await expect(snap).toContainText('申请金额');await expect(snap).not.toContainText('加急说明');});
 test('刷新后草稿、依赖与发布快照保持一致',async({page})=>{await page.goto('/workflows/wf-2');await page.getByTestId('canvas-node-form').click();await page.getByTestId('field-row-amount').getByTitle('删除字段').click();await expect(page.getByTestId('canvas-node-condition')).toHaveClass(/pending/);await page.reload();await expect(page.getByTestId('canvas-node-condition')).toHaveClass(/pending/);await page.getByTestId('canvas-node-form').click();await expect(page.getByTestId('field-row-amount')).toHaveCount(0);await page.goto('/monitor');await page.getByRole('button',{name:'异常',exact:true}).click();await page.getByTestId('instance-row').filter({hasText:'INS-2026-0002'}).click();await expect(page.getByTestId('field-snapshot')).toContainText('申请金额');});
});

test('1440px 桌面视觉与控制台验证',async({page})=>{
 const errors:string[]=[]; page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 for(const path of ['/','/workflows/wf-1','/monitor']){await page.goto(path);await page.waitForTimeout(250);const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth);expect(overflow,`${path} 不应横向溢出`).toBeFalsy()}
 await page.goto('/'); await page.screenshot({path:'test-results/dashboard-1440.png',fullPage:true});
 expect(errors,'浏览器 console 不应出现 error').toEqual([]);
});
